package net.drgmes.dwm.enums;

public enum TardisConsoleUnitControlFlags {
    REQUIRED_MATERIALIZING_SYSTEM,
    REQUIRED_FLIGHT_SYSTEM,
    REQUIRED_SHIELDS_SYSTEM,
    MUST_BE_MATERIALIZED,
    MUST_BE_LANDED,
    DEPENDS_ON_OWNER,
    DEPENDS_ON_SHIELDS_ON,
    DEPENDS_ON_HANDBRAKE_OFF,
}
