plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    mixin {
        add sourceSets.main, 'dwm.refmap.json'
    }

    runs {
        datagen {
            inherit client
            name "Data Generation"
            runDir "run"

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../common/src/main/generated")}"
            vmArg "-Dfabric-api.datagen.strict-validation"

            ideConfigGenerated = true
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}+${rootProject.minecraft_version}"
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"

    if (rootProject.hasProperty("forge_config_api_port_version")) {
        modApi("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${rootProject.forge_config_api_port_version}")
    }

    if (rootProject.hasProperty("imm_ptl_version")) {
        modCompileOnlyApi("com.github.iPortalTeam.ImmersivePortalsMod:q_misc_util:v${rootProject.imm_ptl_version}") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }

        modCompileOnlyApi("com.github.iPortalTeam.ImmersivePortalsMod:imm_ptl_core:v${rootProject.imm_ptl_version}") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }
    }

    if (rootProject.hasProperty("cloth_config_version")) {
        modCompileOnlyApi("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_version}") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }
    }

    if (rootProject.hasProperty("mod_menu_version")) {
        modCompileOnlyApi("com.terraformersmc:modmenu:${rootProject.mod_menu_version}") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }
    }

    if (rootProject.hasProperty("teamreborn_energy_api_version")) {
        modCompileOnlyApi("teamreborn:energy:${rootProject.teamreborn_energy_api_version}") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }
    }

    if (rootProject.hasProperty("ae2_api_version")) {
        modCompileOnlyApi("appeng:appliedenergistics2-forge:${rootProject.ae2_api_version}:api") {
            exclude(group: "net.fabricmc.fabric-api")
            transitive(false)
        }
    }

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive false }
}

processResources {
    inputs.properties(rootProject.ext.attrs)

    filesMatching("fabric.mod.json") {
        expand(rootProject.ext.attrs)
    }
}

shadowJar {
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set "dev-shadow"
}

remapJar {
    injectAccessWidener = true
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    archivesBaseName = "${rootProject.archivesBaseName}-fabric"

    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.mod_id + "-" + project.name
            from components.java
        }
    }
}
