plugins {
    // https://github.com/architectury/architectury-plugin
    id "architectury-plugin" version "3.4-SNAPSHOT"

    // https://github.com/architectury/architectury-loom
    id "dev.architectury.loom" version "1.6-SNAPSHOT" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings "net.fabricmc:yarn:${rootProject.minecraft_version}+${rootProject.yarn_mappings_version}:v2"
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    archivesBaseName = "${rootProject.mod_name}-${rootProject.minecraft_version}"
    version = rootProject.mod_version
    group = rootProject.maven_group

    rootProject.ext.attrs = [
        "modId"                    : rootProject.mod_id,
        "modVersion"               : rootProject.mod_version,
        "modLicense"               : rootProject.mod_license,
        "modAuthors"               : rootProject.mod_authors,
        "modName"                  : rootProject.mod_name,
        "modDescription"           : rootProject.mod_description,
        "modHomepage"              : rootProject.mod_homepage,
        "modSource"                : rootProject.mod_source,
        "minecraftVersion"         : rootProject.minecraft_version,
        "architecturyVersion"      : rootProject.architectury_version,
        "forgeConfigApiPortVersion": rootProject.forge_config_api_port_version,
    ]

    repositories {
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.terraformersmc.com/releases/' }
        maven { url 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/' }

        maven {
            url 'https://modmaven.dev/'
            content { includeGroup 'appeng' }
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 17
    }

    java {
        withSourcesJar()
    }
}
