plugins {
    // https://github.com/architectury/architectury-loom
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false

    // https://github.com/architectury/architectury-plugin
    id 'architectury-plugin' version '3.4-SNAPSHOT'

    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    apply plugin: 'java'

    version = rootProject.mod_version
    group = rootProject.maven_group

    rootProject.ext.attrs = [
        mod_id                       : rootProject.mod_id,
        mod_version                  : rootProject.mod_version,
        mod_license                  : rootProject.mod_license,
        mod_authors                  : rootProject.mod_authors,
        mod_name                     : rootProject.mod_name,
        mod_description              : rootProject.mod_description,
        mod_homepage                 : rootProject.mod_homepage,
        mod_source                   : rootProject.mod_source,
        minecraft_version            : rootProject.minecraft_version,
        fabric_loader_version        : rootProject.fabric_loader_version,
        architectury_api_version     : rootProject.architectury_api_version,
        forge_config_api_port_version: rootProject.forge_config_api_port_version,
    ]

    repositories {
        maven { url 'https://jitpack.io' }
        maven { url 'https://cursemaven.com' }
        maven { url 'https://maven.shedaniel.me' }
        maven { url 'https://maven.terraformersmc.com/releases/' }
        maven { url 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/' }

        maven {
            url 'https://modmaven.dev/'
            content { includeGroup 'appeng' }
        }
    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.mod_name-$rootProject.minecraft_version"
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.minecraft_version+$rootProject.yarn_mappings_version:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
        }
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}
