org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Minecraft properties
minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

# Mod properties
maven_group=net.drgmes.dwm

# Mod Data
mod_id=dwm
mod_version=1.0.14
mod_name=DoctorWhoMod
mod_description=Immerse yourself in the «Doctor Who» universe - travel, explore and survive!
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/dwm
mod_source=https://github.com/drgmes/doctor-who-mod
mod_authors=DrGmes
mod_license=MIT

# Common https://linkie.shedaniel.dev/dependencies
architectury_api_version=13.0.8
yarn_mappings_version=build.3
yarn_mappings_patch_neoforge_version=1.21+build.4

# Fabric https://linkie.shedaniel.dev/dependencies?loader=fabric
fabric_loader_version=0.16.9
fabric_api_version=0.109.0

# NeoForge https://linkie.shedaniel.dev/dependencies?loader=neoforge
neoforge_version=21.1.80

# ClothConfig https://linkie.shedaniel.dev/dependencies?loader=fabric
cloth_config_version=15.0.140

# ModMenu https://linkie.shedaniel.dev/dependencies?loader=fabric
mod_menu_version=11.0.3

# ForgeConfigApiPort https://modrinth.com/mod/forge-config-api-port/versions?l=fabric
forge_config_api_port_version=21.1.2

# DimLib https://github.com/iPortalTeam/DimLib/releases
dim_lib_version=1.1.0-mc1.21.1

# ImmersivePortals https://github.com/iPortalTeam/ImmersivePortalsMod/releases
imm_ptl_version=6.0.4-mc1.21.1

# TechReborn https://maven.fabricmc.net/teamreborn/energy/
teamreborn_energy_api_version=4.1.0

# AppliedEnergistics2 https://modrinth.com/mod/ae2/versions?l=fabric
# ae2_api_version=0.0.0
