modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"

[[mods]]
modId="dwm"
version="${file.jarVersion}"
displayName="Doctor Who Mod"
logoFile="dwm.png"
authors="DrGmes"
description='''...'''

[[dependencies.dwm]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dwm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
