modLoader = "javafml"
loaderVersion = "[4,)"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthors}"
credits = "${modContributors}"
description = "${modDescription}"
logoFile = "assets/${modId}/icon.png"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "architectury"
type = "required"
versionRange = "[${architecturyApiVersion},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "dwm.mixins.json"

[[mixins]]
config = "dwm-common.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
